In [9]:
import numpy as np
from numpy import array
from scipy.linalg import lu
from numpy.linalg import det, inv

In [2]:
A = np.random.randint(1,10,(4,4))
print(A)

[[9 5 9 1]
 [4 3 3 3]
 [4 6 7 8]
 [2 5 9 8]]


In [4]:
P, L, U = lu(A)

In [5]:
print(P)
print(L)
print(U)

[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]
[[1.         0.         0.         0.        ]
 [0.22222222 1.         0.         0.        ]
 [0.44444444 0.97142857 1.         0.        ]
 [0.44444444 0.2        0.63157895 1.        ]]
[[ 9.          5.          9.          1.        ]
 [ 0.          3.88888889  7.          7.77777778]
 [ 0.          0.         -3.8         0.        ]
 [ 0.          0.          0.          1.        ]]


In [6]:
B = P.dot(L).dot(U)
print(B)

[[9. 5. 9. 1.]
 [4. 3. 3. 3.]
 [4. 6. 7. 8.]
 [2. 5. 9. 8.]]


In [11]:
A = array([[2,1,1], [1,3,2], [1,0,0]])
b = array([4,5,6])
if(det(A) != 0):
    B = inv(A)
    x = B.dot(b)
    print(x)
P,L,U = lu(A)
print(P)
print(L)
print(U)

A_new = P.dot(L).dot(U)

[  6.  15. -23.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.5 -0.2  1. ]]
[[ 2.   1.   1. ]
 [ 0.   2.5  1.5]
 [ 0.   0.  -0.2]]


### Dùng scipy.linalg

In [13]:
import scipy.linalg as linalg

LU = linalg.lu_factor(A)

x = linalg.lu_solve(LU, b)
print(LU)
print("Solutions(a,b,c):\n",x)

Test = array([[ 2. ,  1. ,  1. ],
       [ 0.5,  2.5,  1.5],
       [ 0.5, -0.2, -0.2]])
test = array([0, 1, 2])
print(Test.dot(test))

(array([[ 2. ,  1. ,  1. ],
       [ 0.5,  2.5,  1.5],
       [ 0.5, -0.2, -0.2]]), array([0, 1, 2], dtype=int32))
Solutions(a,b,c):
 [  6.  15. -23.]
[ 3.   5.5 -0.6]


In [26]:
Random = np.random.randint(5,10,(4,5)) 

In [27]:
print(Random)

[[8 6 6 7 7]
 [5 6 5 5 6]
 [5 8 5 5 7]
 [8 8 7 7 6]]


In [28]:
from numpy.linalg import qr
Q, R = qr(Random, 'complete')
print(Q)
print(R)

[[-0.59962535  0.58444871 -0.39498355 -0.37796447]
 [-0.37476584 -0.23799716  0.72312372 -0.52915026]
 [-0.37476584 -0.77424391 -0.5043636  -0.07559289]
 [-0.59962535  0.04820196  0.25825847  0.75592895]]
[[-13.34166406 -13.64147674 -11.54278801 -12.14241336 -12.66708554]
 [  0.          -3.7296263   -1.21709938  -0.63265067  -2.46733759]
 [  0.           0.           0.53170862   0.13672507  -0.40713688]
 [  0.           0.           0.          -0.37796447  -1.81422947]]


In [29]:
print(Q.dot(R))

[[8. 6. 6. 7. 7.]
 [5. 6. 5. 5. 6.]
 [5. 8. 5. 5. 7.]
 [8. 8. 7. 7. 6.]]


In [30]:
CholeskyR = np.random.randint(3,9,(3,3))
print(CholeskyR)

[[5 5 7]
 [4 5 4]
 [6 6 7]]
