In [1]:
import numpy as np

In [2]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[8,9,10]]])
print(a)
print(a.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 8  9 10]]]
(2, 2, 3)


In [3]:
print(a[0,1])

[4 5 6]


In [4]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [16]:
b = a.reshape(2,3,4)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [13]:
print(b[0,...,0])
b1 = b[1]
print(b1)


[0 4 8]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [14]:
print(b[1,1,...])
print(b1[1,...])

[16 17 18 19]
[16 17 18 19]


In [12]:
print(b[1,...,2])
print(b1[...,2])

[14 18 22]
[14 18 22]


In [17]:
a = np.array([[23,56,12,34],[12,57,32,11],[38,32,45,21]])
print(a)


[[23 56 12 34]
 [12 57 32 11]
 [38 32 45 21]]


In [18]:
print(np.amax(a))
print(np.amin(a))

57
11


In [19]:
# min, max theo dong
print(np.amax(a,1))
print(np.amin(a,1))

[56 57 45]
[12 11 21]


In [20]:
# min, max theo cot
print(np.amax(a,0))
print(np.amin(a,0))

[38 57 45 34]
[12 32 12 11]
