In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])
print(a)


[1 2 3 4 5 6]


In [3]:
print(a.shape)

(6,)


In [5]:
b = np.arange(20)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
c = np.arange(10, 20, 2)
print(c)

[10 12 14 16 18]


In [7]:
# them
c = np.append(c,[27,23,21])
print(c)


[10 12 14 16 18 27 23 21]


In [8]:
# sua
c[3] = 61
print(c)

[10 12 14 61 18 27 23 21]


In [10]:
# chen
print('before:',c)
c = np.insert(c,1,[45,36,67])
print('after:',c)

before: [10 45 12 14 61 18 27 23 21]
after: [10 45 36 67 45 12 14 61 18 27 23 21]


In [13]:
a = np.array([23,34,45,56,67,45,32,91,21])
print(a)


[23 34 45 56 67 45 32 91 21]


In [15]:
s = slice(3,8,2) # 3,5,7
print(a[s]) # 56,45,91
print(a[s][0])
print(a[s][1])
print(a[s][2])

[56 45 91]
56
45
91


In [19]:
a = np.array([23,34,45,56,67,45,32,91,21])
print(a)
b = a*a
print(b)

[23 34 45 56 67 45 32 91 21]
[ 529 1156 2025 3136 4489 2025 1024 8281  441]


In [20]:
b = a+1
print(b)

[24 35 46 57 68 46 33 92 22]


In [21]:
print(23*23)

529


In [24]:
a = np.array([23,34,45,56,67,45,32,91,21])
b = np.array([23,34,45,56,67,45,32])
for i in range(len(a)-len(b)):
    b = np.append(b,[0])
print(a+b)    

[ 46  68  90 112 134  90  64  91  21]


In [25]:
a = np.array([23,34,45,56,67,45,32,91,21])
print(a)
b = np.sort(a)
print(b)

[23 34 45 56 67 45 32 91 21]
[21 23 32 34 45 45 56 67 91]


In [27]:
c = b[::-1]
print(c)

[91 67 56 45 45 34 32 23 21]
