Tính toán PCA

In [1]:
import numpy as np

In [24]:
A = np.random.randint(1,256,(3,3))
A.shape

(3, 3)

In [25]:
A[0:10]

array([[ 59,  79,  16],
       [ 63,  35, 123],
       [190,  46, 213]])

In [26]:
# colmns' means
M = np.mean(A.T, axis = 1) //theo dòng
N = np.mean(A, axis = 0) // theo cột
print(M)
N

SyntaxError: invalid syntax (<ipython-input-26-bbb166cc6c74>, line 2)

## Array - Vector

In [23]:
TempArray = np.array([[7,8,9],[7,5,6], [7,9,8]])
tempvector = np.array([1,2,3])
print(TempArray)
print(tempvector)
print(TempArray - tempvector)

[[7 8 9]
 [7 5 6]
 [7 9 8]]
[1 2 3]
[[6 6 6]
 [6 3 3]
 [6 7 5]]


In [19]:
# center columns by subtracting column means
C = A - M
C[0:10]

array([[  34.09833333, -121.588     ,   69.50833333],
       [ -78.90166667, -108.588     ,   43.50833333],
       [  49.09833333,    7.412     , -113.49166667],
       [  16.09833333,  -58.588     ,  -18.49166667],
       [ -43.90166667,   94.412     ,    2.50833333],
       [ 116.09833333,  -83.588     ,  -40.49166667],
       [  61.09833333,   35.412     ,   99.50833333],
       [ 110.09833333,  -48.588     ,  126.50833333],
       [  39.09833333,   65.412     ,  -82.49166667],
       [-121.90166667,  -35.588     ,   35.50833333]])

In [20]:
V = np.cov(C.T)

In [18]:
values, vectors = np.linalg.eig(V)
values

array([5579.23709963, 5408.88957414, 5349.3640069 ])