# Chapter 3 - exercise 1: Hãy thực hiện các yêu cầu sau:
1. Tạo numpy array có giá trị từ 0 - 9, in array, type, shape
2. Từ numpy array ở câu 1 => tạo arr_odd và arr_even => in 2 array mới này
3. Từ numpy array ở câu 1 => tạo arr_update_1 với các phần tử chẵn giữ nguyên, các phần tử lẻ thay bằng 100 => in kết quả
4. Từ 2 array => tạo arr mới chỉ chứa các phần tử xuất hiện ở cả 2 array, lấy duy nhất, dùng np.intersect1d(a,b)
5. Từ 2 array a và b ở câu trên => Tạo array mới chỉ chứa các phần tử chỉ xuất hiện ở array a, dùng np.setdiff1d(a,b)
6. Cho array e, tạo array f chỉ chứa các phần tử có giá trị từ 5 đến 10 của e
7. Tạo array có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1
8. Tạo array có giá trị từ 10 đến 24
9. Cho array k => tạo array l từ k với các phần tử đếu khác 0
10. Từ array của câu trên, thêm 2 phần tử có giá trị là 10, 20 vào cuối array
11. Từ array của câu trên, thêm phần tử có giá trị 100 vào index = 5
12. Từ array của câu trên, xóa phần tử index = 0, 1, 2

In [1]:
import numpy as np

In [3]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(10,)


In [6]:
arr_odd = a[a % 2 == 0]
arr_even = a[a % 2 != 0]

print(arr_odd)
print(arr_even)

[0 2 4 6 8]
[1 3 5 7 9]


In [13]:
arr_update_1 = a
arr_update_1[arr_update_1 % 2 != 0] = 100
print(arr_update_1)
print(a)

[  0 100   2 100   4 100   6 100   8 100]
[  0 100   2 100   4 100   6 100   8 100]


In [11]:
arr_update_2 = np.intersect1d(arr_update_1, a)
print(arr_update_2)

[  0   2   4   6   8 100]


In [14]:
arr_update_3 = np.setdiff1d(a,arr_update_1)
print(arr_update_3)

[]


In [15]:
e = np.arange(20)
indexes = np.where(e >= 5)
print(indexes)
print(e[indexes])

(array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
      dtype=int64),)
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [16]:
print(np.extract(e >= 5, e))

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [18]:
print(e[(e >= 5) & (e <= 10)])

[ 5  6  7  8  9 10]


In [21]:
g = np.zeros(10)
print(g)
g[4] = 1
print(g)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [22]:
c = np.arange(12,25)
print(c)

[12 13 14 15 16 17 18 19 20 21 22 23 24]


In [31]:
k = np.array([1,2,4,6,0,43,5, 0])
l = k[k != 0]
n = k[k.nonzero()]
print(l)
print(n)

[ 1  2  4  6 43  5]
[ 1  2  4  6 43  5]


In [32]:
l = np.append(l, [10,20])
print(l)

[ 1  2  4  6 43  5 10 20]


In [33]:
l = np.insert(l, 5, 100)
print(l)

[  1   2   4   6  43 100   5  10  20]


In [34]:
l = np.delete(l, [0,1,2])
print(l)

[  6  43 100   5  10  20]
