## Chapter 3 - Exercise 2: Đọc và chuyển dữ liệu sau đó tính BMI theo điều kiện, truy xuất dữ liệu
### Dữ liệu được trích xuất từ http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_MLB_HeightsWeights
### Cho tập tin heights_1.txt, weights_1.txt => hãy chép dữ liệu từ tập tin này vào list là height, weight
1. Chuyển list height thành numpy array np_height => In shape của np_height
2. Chuyển list weight thành numpy array np_weight => In shape của np_weight
3. Cho hệ số quy đổi từ inch sang m là 0.0254 => Hãy tạo ra numpy array np_height_m dựa trên công thức: np_height * hệ số quy đổi này => In kết quả
4. Cho hệ số quy đổi từ pound sang kg là 0.453592 => Hãy tạo ra numpy array np_weight_kg dựa trên công thức: np_weight * hệ số quy đổi này => In kết quả
5. Tính và in BMI của np_height_m và np_weight_kg theo công thức BIM = Cân nặng / (Chiều cao * Chiều cao)
6. In weight ở vị trí index 50
7. In ra array con lấy từ index 100 đến index 110 (lấy cả index 110)

In [1]:
import numpy as np

In [11]:
heights = np.loadtxt('heights_1.txt', comments='#', delimiter=',', unpack=False)
print(heights)
print(type(heights))
print(heights.shape)

[74. 74. 72. ... 75. 75. 73.]
<class 'numpy.ndarray'>
(1015,)


In [12]:
np_heights = np.array(heights)
print(np_heights)
print(type(np_heights))
print(np_heights.shape)

[74. 74. 72. ... 75. 75. 73.]
<class 'numpy.ndarray'>
(1015,)


In [33]:
with open('weights_1.txt', 'r') as file:
    data = file.read()
    data = data.replace('[', '').replace(']', '')
    listString = data.split(',')
    np_weights = np.array(list(map(lambda x: int(x), listString)))

In [34]:
print(np_weights)
print(np_weights.shape)
print(type(np_weights))

[180 215 210 ... 205 190 195]
(1015,)
<class 'numpy.ndarray'>


In [35]:
print(len(np_weights))

1015


In [36]:
np_height_m = np_heights * 0.0254
print(np_height_m)

[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]


In [39]:
np_weight_kg = np_weights * 0.453502
print(np_weight_kg)

[81.63036 97.50293 95.23542 ... 92.96791 86.16538 88.43289]


In [40]:
bmi = np_weight_kg/(np_height_m ** 2)
print(bmi)

[23.10579092 27.59858359 28.47515359 ... 25.61787532 23.74339664
 25.72175899]


In [ ]:
print()