## Chapter 3 - Exercise 3
1. Tạo array 3x3 với tất cả các giá trị đều là True. In array
2. Cho array 1D có 9 phần tử 0-8 => chuyển thành array 2D (3x3) => In array. Chuyển cột 1 sang cột 3 và ngược lại. => In array
3. Sử dụng array 2D của câu trên, chuyển dòng 1 sang dòng 2 và ngược lại => In array
4. Sử dụng array 2D của câu trên, Đảo ngược các dòng của array 2D => In array
5. Sử dụng array 2D của câu trên, Đảo ngược các cột của array 2D = > In array
6. Cho h = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]]), kiểm tra xem trong array có giá trị rỗng nào không?
7. Sử dụng array 2D của câu trên, thay thế giá trị null bằng 0

In [1]:
import numpy as np

In [2]:
a = np.ones((3,3), dtype=bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [7]:
A = np.array([5,5,8,29,8,8,9,0,8])
print(A)

[ 5  5  8 29  8  8  9  0  8]


In [8]:
C = A.reshape(3,3)
print(C)

[[ 5  5  8]
 [29  8  8]
 [ 9  0  8]]


In [9]:
C_Change_Col = C[:, [2,1,0]]
print(C_Change_Col)

[[ 8  5  5]
 [ 8  8 29]
 [ 8  0  9]]
