In [4]:
from numpy.linalg import eig
import numpy as np

In [6]:
A = np.array([[1,3,5], [2,4,6], [7,8,9]])
A

array([[1, 3, 5],
       [2, 4, 6],
       [7, 8, 9]])

In [8]:
values, vectors = eig(A)
values

array([ 1.64339811e+01, -2.43398113e+00, -3.67161364e-16])

In [11]:
vectors

array([[ 0.35321681,  0.5923436 ,  0.40824829],
       [ 0.45205763,  0.44327356, -0.81649658],
       [ 0.81907374, -0.67278348,  0.40824829]])

In [13]:
vectors[:, 0]

array([0.35321681, 0.45205763, 0.81907374])

In [14]:
vectors[0, :]

array([0.35321681, 0.5923436 , 0.40824829])