In [17]:
import numpy as np
import random
import scipy
from scipy.linalg import lu

In [16]:
def create_matrix_random(m,n, start, end):
    lst = []
    for i in range(m):
        lst_sub = []
        for j in range(n):
            x = random.randint(start, end+1)
            lst_sub.append(x)
        lst.append(lst_sub)    
    return np.array(lst)   

In [20]:
A = create_matrix_random(4,4,1,10)
print(A)

[[4 2 5 1]
 [9 2 6 1]
 [5 8 7 6]
 [2 2 8 1]]


In [21]:
P, L, U = lu(A)

In [22]:
B = P.dot(L).dot(U)
print(B)

[[4. 2. 5. 1.]
 [9. 2. 6. 1.]
 [5. 8. 7. 6.]
 [2. 2. 8. 1.]]



Câu 2: Hãy dùng LU Decompostion để làm lại bài toán này:

    Cho:
    2a + b + c = 4
    a + 3b + 2c = 5
    a = 6
    Quy về Ax = B. Sau đó giải tìm x
    Phân tích thành các thành phần P, L, U từ A. In kết quả
    Tại tạo ma trận A từ các thành phần P, L, U với tên là A_new



Ta có mảng 2 chiều A

In [23]:
A = np.array([[2,1,1],[1,3,2],[1,0,0]])

Ta có vector b

In [ ]:
b = np.array([4,5,6])

Tính LU decomposition từ A

In [24]:
P, L, U = lu(A)

In [25]:
print(P)
print(L)
print(U)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.5 -0.2  1. ]]
[[ 2.   1.   1. ]
 [ 0.   2.5  1.5]
 [ 0.   0.  -0.2]]


In [26]:
A_new = P.dot(L).dot(U)

In [27]:
print(A_new)

[[ 2.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  3.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00 -2.77555756e-17  2.77555756e-17]]



## Câu 3: QA Decomposition

    Tạo ma trận C(4x5) chứa các giá trị ngẫu nhiên trong khoảng 5 - 10
    Phân tích thành các thành phần Q, R. In kết quả
    Tái tạo ma trận D từ các thành phần Q, R.



QA phân rã ma trân mxn với m != n

In [32]:
C = create_matrix_random(4,5,5,10)
print(C)

[[ 9 11  5 10 11]
 [11 10  7  8  7]
 [ 6 10  8  9  6]
 [ 9 11  8 10  6]]


In [33]:
from numpy.linalg import qr

In [35]:
Q, R = qr(C, 'complete')
print(Q)
print(R)

[[-0.50390326  0.14773636  0.84741269 -0.07840406]
 [-0.61588176 -0.64344061 -0.28669341 -0.35281827]
 [-0.33593551  0.73643202 -0.37031232 -0.4557236 ]
 [-0.50390326  0.14773636 -0.25013475  0.81344212]]
[[-17.8605711  -20.6040444  -13.54939877 -18.02853885 -14.89314079]
 [  0.           4.18011414   3.30794465   4.4350906    2.42602606]
 [  0.           0.          -2.73336703   0.34642121   3.5920033 ]
 [  0.           0.           0.           0.42632207  -1.1858614 ]]


In [36]:
D = Q.dot(R)
print(D)

[[ 9. 11.  5. 10. 11.]
 [11. 10.  7.  8.  7.]
 [ 6. 10.  8.  9.  6.]
 [ 9. 11.  8. 10.  6.]]



## Câu 4: Cholesky Decomposition

    Tạo ma trận E(3x3) vuông chứa các giá trị ngẫu nhiên trong khoảng 3 - 9.
    Từ đó chuyển E thành ma trận vuông đối xứng theo tam giác dưới dường chéo chính
    Kiểm tra nếu mọi thành phần đều không âm thì:
        Phân tích thành L. In kết quả
        Tái tạo ma trận F từ các thành phần L.L.T
    Ngược lại thì thông báo E có thành phần âm
    Chú ý: dùng np.linalg.eigvalsh(E) để kiểm tra xem mọi thành phần có âm hay không
    Mở rộng: Thực hiện việc tạo ma trận vuông đối xứng với mọi thành phần đều không âm và phân tích.



In [57]:
from numpy.linalg import cholesky, eigvalsh, eig

In [44]:
E = create_matrix_random(3,3,3,9)
print(E)

[[ 4  5  8]
 [10  9  8]
 [ 8  5  8]]


In [45]:
E.shape

(3, 3)

In [46]:
for i in range(E.shape[0]):
    for j in range(i):
        E[j][i] = E[i][j]
print(E)

[[ 4 10  8]
 [10  9  5]
 [ 8  5  8]]


In [65]:
test = np.linalg.eigvalsh(E)

In [67]:
flag = np.all(test>0)

In [64]:
print(eigvalsh(Temp))

[-4.92715836  3.51333209 22.41382627]


Cholesky dành cho ma trận vuông đối xứng

In [68]:
if flag==True:
    L = cholesky(E)
    print(L)
    F = L.dot(L.T)
else:
    print('E not positive definite')

E not positive definite


In [70]:
def create_matrix_positive_definite(m,n,start,end):
    E = None
    flag = False
    while flag == False:
        E = create_matrix_random(m,n,start,end)
        for i in range(m):
            for j in range(i):
                E[j][i] = E[i][j]
        test = eigvalsh(E)
        flag = np.all(test>0)
    return E

In [74]:
E = create_matrix_positive_definite(3,3,3,9)
print(E)

[[ 5  3  5]
 [ 3 10  6]
 [ 5  6 10]]


In [76]:
L = cholesky(E)
print(L.dot(L.T))

[[ 5.  3.  5.]
 [ 3. 10.  6.]
 [ 5.  6. 10.]]
