In [31]:
import sys

In [32]:
sys.path

['C:\\aidev - ntnvu\\machine_learning\\lds3_mathematics_data_science\\2019_07_28\\home\\bai_tap_trong_sach',
 'c:\\users\\aidev\\appdata\\local\\programs\\python\\python37\\python37.zip',
 'c:\\users\\aidev\\appdata\\local\\programs\\python\\python37\\DLLs',
 'c:\\users\\aidev\\appdata\\local\\programs\\python\\python37\\lib',
 'c:\\users\\aidev\\appdata\\local\\programs\\python\\python37',
 '',
 'c:\\users\\aidev\\appdata\\local\\programs\\python\\python37\\lib\\site-packages',
 'c:\\users\\aidev\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\AIDEV\\.ipython']

In [2]:
from mylib import *


Câu 1:

    Tạo ma trận A(5x5) với các giá trị ngẫu nhiên từ 1 đến 10
    Phân tích thành eiganvalues và eiganvectors
    Xác nhận eigenvector đầu tiên theo dot và theo eigenvalue có bằng nhau?
    Nấu bằng nhau thi tái cấu trúc A từ các eigenvector và eigenvalue



In [3]:
import numpy as np

In [14]:
from numpy.linalg import eig, inv
from numpy import diag

In [17]:
A = create_matrix_random(5,5,1,10)
print(A)

[[ 1  8  9  8  6]
 [ 3  2 11  2  1]
 [ 3  3  3  6  9]
 [ 1  5  9 11 11]
 [ 6  3 11  6  6]]


In [18]:
values, vectors = eig(A)

In [9]:
B = A.dot(vectors[:, 0])
print(B)

[-14.77945416+0.j -10.34745672+0.j -17.13266978+0.j -11.51581483+0.j
 -11.74826776+0.j]


In [11]:
C = vectors[:,0] * values[0]
print(C)

[-14.77945416+0.j -10.34745672+0.j -17.13266978+0.j -11.51581483+0.j
 -11.74826776+0.j]


In [19]:
Q = vectors
R = inv(Q)
L = diag(values)
A_new = Q.dot(L).dot(R)
print(A_new)

[[ 1.+7.73100705e-16j  8.-5.65711671e-16j  9.-6.59790627e-16j
   8.+4.44256237e-16j  6.+4.41082089e-16j]
 [ 3.+8.26863399e-16j  2.-7.94698841e-16j 11.-9.17969444e-16j
   2.+2.18728390e-16j  1.+1.10132788e-15j]
 [ 3.+9.06022715e-16j  3.-6.59062450e-16j  3.-3.75317995e-16j
   6.+1.86916062e-16j  9.-7.48342926e-16j]
 [ 1.+1.13944402e-15j  5.-4.50288308e-16j  9.-7.40601992e-16j
  11.+5.67175189e-16j 11.-1.95522588e-16j]
 [ 6.+1.38671129e-15j  3.-1.55854123e-15j 11.-1.03977201e-15j
   6.+1.59190275e-16j  6.+3.33825288e-16j]]


Câu 2:

    Tạo ma trận P(4x4) vuông với các giá trị ngẫu nhiên tứ 1 đến 9
    Tạo ma trận đối xứng S=P.PT

Tìm eigenvalues và eigenvectors của S

In [21]:
from numpy.linalg import eig, inv
from numpy import diag

In [23]:
P = create_matrix_random(4,4,1,9)
print(P)

[[10  2  3  2]
 [ 1  2  3  5]
 [10  5  9  2]
 [ 5  2  4  7]]


In [24]:
S = P.dot(P.T)
print(S)

[[117  33 141  80]
 [ 33  39  57  56]
 [141  57 210 110]
 [ 80  56 110  94]]


In [26]:
vectors, values = eig(P)
print(values)
print("-----------")
print(vectors)

[[-0.42859596  0.04530349 -0.39174332 -0.03248959]
 [-0.29847932 -0.87134412  0.69723995  0.4859082 ]
 [-0.70449329  0.48406056 -0.17209892 -0.64847248]
 [-0.48052555 -0.06627523  0.57513092  0.58508212]]
-----------
[18.56631869  0.66171239  4.82200485  3.94996406]
