In [4]:
from numpy.linalg import qr
import numpy as np

In [5]:
A = np.array([[1,2,3], [3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


$c_{ij} = \displaystyle\sum_{k=1}^{n} a_{ik}b_{kj}$

$c_{ij} = \displaystyle\sum_{k=1}^{n} a_{ik}b_{kj}$

$c_{ij}$

$\displaystyle\sum_{k=1}^{n}$

In [19]:
from numpy.linalg import eig, inv, det
from numpy import diag
A = np.array([[1,3,5], [2,4,6], [7,8,9]])

In [10]:
values, vectors = eig(A)

In [11]:
print(values)

[ 1.64339811e+01 -2.43398113e+00 -3.67161364e-16]


In [13]:
print(vectors[:, 0])
print(vectors)

[0.35321681 0.45205763 0.81907374]
[[ 0.35321681  0.5923436   0.40824829]
 [ 0.45205763  0.44327356 -0.81649658]
 [ 0.81907374 -0.67278348  0.40824829]]


In [15]:
B = A.dot(vectors[:,0])
print(B)

c = vectors[:,0] * values[0]
print(c)

[ 5.80475838  7.42910655 13.46064233]
[ 5.80475838  7.42910655 13.46064233]


In [20]:
Q = vectors
R = inv(Q)
L = diag(values)

B = Q.dot(L).dot(R)
print(B)

[[1. 3. 5.]
 [2. 4. 6.]
 [7. 8. 9.]]
