## Chapter 3 - Exercise 3
1. Tạo array 3x3 với tất cả các giá trị đều là True. In array
2. Cho array 1D có 9 phần tử 0-8 => chuyển thành array 2D (3x3) => In array. Chuyển cột 1 sang cột 3 và ngược lại. => In array
3. Sử dụng array 2D của câu trên, chuyển dòng 1 sang dòng 2 và ngược lại => In array
4. Sử dụng array 2D của câu trên, Đảo ngược các dòng của array 2D => In array
5. Sử dụng array 2D của câu trên, Đảo ngược các cột của array 2D = > In array
6. Cho h = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]]), kiểm tra xem trong array có giá trị rỗng nào không?
7. Sử dụng array 2D của câu trên, thay thế giá trị null bằng 0

In [20]:
import numpy as np

In [22]:
# In 1 phần của array
a1 = np.arange(100)
np.set_printoptions(threshold=15)
print(a1)

[ 0  1  2 ... 97 98 99]


In [23]:
# In toàn bộ array
np.set_printoptions(threshold=0)
print(a1)

[ 0  1  2 ... 97 98 99]


In [4]:
# Câu 1: Tạo array 3x3 với tất cả các giá trị đều là True. In array
a = np.ones((3,3), dtype=bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
# Câu 2: Cho array 1D có 9 phần tử 0-8 => chuyển thành array 2D 3x3 => In kết quả. Chuyển cột 1 sang cột 3 và ngược lại.
b = np.array(range(9))
print(b)

[0 1 2 ... 6 7 8]


In [6]:
c = b.reshape(3,3)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
d = c[:, [2,1,0]]
print(d)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [8]:
# Câu 3: Sử dụng array 2D của câu trên, chuyển dòng 1 sang dòng 2 và ngược lại => In array
e = d[[1,0,2], :]
print(e)

[[5 4 3]
 [2 1 0]
 [8 7 6]]


In [9]:
# Câu 4: Đảo ngược các dòng của array 2D
f = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f)
print("Reverse:")
print(f[::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reverse:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [10]:
# Câu 5: Đảo ngược các cột của array 2D
g = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(g)
print("Reverse:")
print(g[:, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reverse:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [11]:
import numpy as np
# Câu 6: Kiểm tra xem trong array có giá trị null nào không
h = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
print(h)
print("Have nan? : ", np.isnan(h).any())

[[ 1.  2.  3.]
 [nan  5.  6.]
 [ 7. nan  9.]
 [ 4.  5.  6.]]
Have nan? :  True


In [12]:
# Câu 7: Thay thế giá trị null bằng 0
print("Before:")
print(h)
h[np.isnan(h)] = 0
print("After:")
print(h)

Before:
[[ 1.  2.  3.]
 [nan  5.  6.]
 [ 7. nan  9.]
 [ 4.  5.  6.]]
After:
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
