In [1]:
import numpy as np

In [16]:
b = np.array(range(9))
b.shape = (3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
c = b[:,[2,1,0]]
print(c)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [17]:
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
c = np.array(b[:,0])
print(c)

[0 3 6]


In [19]:
b[:,0] = b[:,2]
b[:,2] = c
print(b)

[[2 1 0]
 [5 4 3]
 [8 7 6]]
