In [1]:
import numpy as np

#### cal_matrices

In [2]:
def cal_matrices(op, m1, m2):
    if(op == '+'):
        return m1 + m2
    if(op == '-'):
        return m1 - m2
    if(op == '*'):
        return m1 * m2
    if(op == '/'):
        return m1 / m2

In [3]:
u = np.array([[2,3,4],[5,6,7]])
v = np.array([[5,6,7],[8,9,10]])

print(cal_matrices("+", u, v))

[[ 7  9 11]
 [13 15 17]]


In [7]:
a = np.array([[1,2,3], [7,8,9]])
b = np.array([[2,5,5],[6,7,9]])

print(cal_matrices("*", a, b))

[[ 2 10 15]
 [42 56 81]]
