In [2]:
import numpy as np

In [3]:
def cal_scalar_mult(v,b):
    return v * b

In [4]:
a = np.array([[1,2,3], [4,5,6]])
print(cal_scalar_mult(a,5))

[[ 5 10 15]
 [20 25 30]]


## câu 2
#### create_matrix: nhập vào 1 ma trận
#### create_vector: nhập vào 1 vector

In [5]:
def create_matrix(m,n):
    lst = []
    for i in range(m):
        lst_sub = []
        for j in range(n):
            s = "M[" + str(i+1) + "," + str(j+1) + "]:"
            x = eval(input(s))
            lst_sub.append(x)
        lst.append(lst_sub)    
    return np.array(lst)    

In [6]:
def create_vector(n):
    lst = []
    for i in range(n):
        s = 'v[' + str(i+1) + "]:"
        x = eval(input(s))
        lst.append(x)
    return np.array(lst)

In [7]:
r = int(input("row: "))
c = int(input("col: "))
A = create_matrix(r,c)

row: 3
col: 3
M[1,1]:1
M[1,2]:2
M[1,3]:3
M[2,1]:4
M[2,2]:5
M[2,3]:6
M[3,1]:7
M[3,2]:8
M[3,3]:9


In [8]:
n = int(input())
v = create_vector(n)

3
v[1]:1
v[2]:2
v[3]:3


In [9]:
print(A * v)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


## Câu 3

In [10]:
import random

In [11]:
def create_matrix_random(m,n, start, end):
    lst = []
    for i in range(m):
        lst_sub = []
        for j in range(n):
            x = random.randint(start, end+1)
            lst_sub.append(x)
        lst.append(lst_sub)    
    return np.array(lst)   

In [17]:
def create_vector_random(n, start, end):
    lst = []
    for i in range(n):        
        x = random.randint(start, end+1)
        lst.append(x)
    return np.array(lst)

In [13]:
r = int(input("row: "))
c = int(input("col: "))
start = int(input("start: "))
end = int(input("end: "))
RandomA = create_matrix_random(r,c,start, end)

row: 10
col: 5
start: 2
end: 9


In [14]:
print(RandomA)

[[ 5  5  2  3  2]
 [ 7  3  2  2 10]
 [ 8  2  2  6  4]
 [ 7  4  2  9 10]
 [ 3  7  7  2 10]
 [10 10  3  8  4]
 [10  6  2  9  4]
 [ 3  7  8 10  9]
 [ 2  9  4  5  5]
 [ 3  6  2  3  6]]


In [18]:
randomv = create_vector_random(5, 1, 10)

In [19]:
print(randomv)

[ 8  7 10  4  9]


In [20]:
print(RandomA * randomv)

[[40 35 20 12 18]
 [56 21 20  8 90]
 [64 14 20 24 36]
 [56 28 20 36 90]
 [24 49 70  8 90]
 [80 70 30 32 36]
 [80 42 20 36 36]
 [24 49 80 40 81]
 [16 63 40 20 45]
 [24 42 20 12 54]]


In [21]:
print(RandomA.dot(randomv))

[125 195 158 230 241 248 214 274 184 152]
