In [15]:
import numpy as np

def cal_vector(op, u, v):
    result = None
    if op == '+':
        result = u + v
    elif op == '-':
        result = u - v
    elif op == '*':
        result = u * v
    elif op == '/':
        result = u / v
    elif op == 'dot':
        if u.shape[0] == v.shape[0]:            
            result = u.dot(v)
        else:
            result = 'khong cung do dai'
    else:
        result = None
    return result

In [18]:
u = np.array([1,2,3,4,5,6])
v = np.array([2,3,4,5,6,8])
print(cal_vector('+', u, v))
print(cal_vector('-', u, v))
print(cal_vector('*', u, v))
print(cal_vector('/', u, v))
print(cal_vector('dot', u, v))

[ 3  5  7  9 11 14]
[-1 -1 -1 -1 -1 -2]
[ 2  6 12 20 30 48]
[0.5        0.66666667 0.75       0.8        0.83333333 0.75      ]
118


In [20]:
import numpy as np
from numpy.linalg import norm
import math

def cal_vector_norm(t,v):
    result = None
    if t == 'L1':
        result = norm(v, 1)
    elif t == 'L2':
        result = norm(v)
    elif t == 'Max':
        result = norm(v, math.inf)
    else:
        result = None
    return result
    

In [21]:
v = np.array([1, 2, -3, -4, 5])
print(cal_vector_norm('L1', v))
print(cal_vector_norm('L2', v))
print(cal_vector_norm('Max', v))

15.0
7.416198487095663
5.0
