In [7]:
import numpy as np
import random

In [9]:
def create_matrix(m,n):
    lst = []
    for i in range(m):
        lst_sub = []
        for j in range(n):
            s = 'M[' + str(i+1) + ',' + str(j+1) + ']'
            x = eval(input(s))
            lst_sub.append(x)
        lst.append(lst_sub)
    return np.array(lst)

In [10]:
A = create_matrix(3,3)

M[1,1]1
M[1,2]2
M[1,3]3
M[2,1]4
M[2,2]5
M[2,3]6
M[3,1]7
M[3,2]8
M[3,3]9


In [11]:
print(A)
print(type(A))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [15]:
def create_matrix_auto(m,n,start,end):
    lst = []
    for i in range(m):
        lst_sub = []
        for j in range(n):
            x = random.randint(start,end+1)
            lst_sub.append(x)
        lst.append(lst_sub)
    return np.array(lst)        

In [33]:
def create_vector_auto(n,start,end):
    lst = []
    for j in range(n):
        x = random.randint(start,end+1)
        lst.append(x)
    return np.array(lst)        

In [16]:
B = create_matrix_auto(3,3,1,4)

In [17]:
print(B)
print(type(B))

[[2 4 1]
 [4 4 4]
 [3 5 3]]
<class 'numpy.ndarray'>


In [18]:
X = create_matrix_auto(3,4,0,11)

In [37]:
XT = X.T
XT1 = X.transpose()

In [38]:
print(X)
print(XT)
print(XT1)

[[10 10  0  8]
 [ 2  6  4  4]
 [ 1 11  5  5]]
[[10  2  1]
 [10  6 11]
 [ 0  4  5]
 [ 8  4  5]]
[[10  2  1]
 [10  6 11]
 [ 0  4  5]
 [ 8  4  5]]


In [21]:
print(XT.dot(X))

[[105 123  13  93]
 [123 257  79 159]
 [ 13  79  41  41]
 [ 93 159  41 105]]


In [23]:
A = create_matrix_auto(2,2,1,4)

In [30]:
from numpy.linalg import det, inv, matrix_rank
print(A)
print(det(A))

[[2 4]
 [5 5]]
-9.999999999999998


In [27]:
print(inv(A))

[[-0.5  0.4]
 [ 0.5 -0.2]]


In [28]:
C = create_matrix_auto(5,5,5,10)

In [31]:
print(C)
print(np.trace(C))
print(det(C))
print(matrix_rank(C))

[[ 7  7  8  7 11]
 [ 5  6  7 10  8]
 [ 5  9 11  5  6]
 [11 11  9  7 10]
 [ 9 10  6  5 10]]
41
-3756.000000000001
5


In [34]:
A = create_matrix_auto(3,3,1,6)
b = create_vector_auto(3, 1, 3)

In [35]:
print(A)
print(b)

[[6 7 7]
 [6 1 4]
 [1 2 6]]
[2 3 3]


In [36]:
if det(A) != 0:
    B = inv(A)
    x = B.dot(b) 
    print(x)

[ 0.1572327  -0.48427673  0.63522013]
