In [10]:
import numpy as np

def cal_matrices(op, m1, m2):
    result = None
    if op == '+':
        result = m1 + m2
    elif op == '-':
        result = m1 - m2
    elif op == '*':
        result = m1 * m2
    elif op == '/':
        result = m1 / m2
    elif op == 'dot':
        if m1.shape[1] == m2.shape[0]:
            result = m1.dot(m2)
        else:
            result = 'So cot ma tran 1 phai bang so dong ma tran 2'
    else:
        result = None
    return result

In [26]:
A = np.array([[1,2,4], [2,3,5], [4,5,6]])
B = np.array([[1,0,0], [0,1,0], [0,0,1]])
C = np.array([2,3,2])
D = np.array([2,3,2])
E = 2

print(B.dot(D))
print(C * D)

[2 3 2]
[4 9 4]


In [27]:
A = np.array([[1,2,4], [2,3,5], [4,5,6]])

print (A)
print (A.T)

[[1 2 4]
 [2 3 5]
 [4 5 6]]
[[1 2 4]
 [2 3 5]
 [4 5 6]]


In [28]:
C = A.T
print (C)

[[1 2 4]
 [2 3 5]
 [4 5 6]]


In [42]:
X = np.array([[1,2,3],[4,5,6], [5,6,8]])
from numpy.linalg import det,inv,matrix_rank

print(det(X))

-2.9999999999999956


In [43]:
Y = inv(X)
print(Y)

[[-1.33333333 -0.66666667  1.        ]
 [ 0.66666667  2.33333333 -2.        ]
 [ 0.33333333 -1.33333333  1.        ]]


In [44]:
print(np.trace(X))

14


In [49]:
Z = np.array([[1,2],[2,2]])                                                                                                                          
print(inv(Z))
    

[[-1.   1. ]
 [ 1.  -0.5]]


In [46]:
print(matrix_rank(Z))


2
